[project]
name = "schocken"
version = "0.0.1"
description = "Python implementation of the dice game Schocken (German)"
authors = [{ name = "Mats H" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

